# TODO: persist data in postgres contianers 
# and redis how (okay maybe not redis)
services:
  postgres:
    image: postgres:13
    container_name: postgres
    user: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]

  redis:
    image: redis:6
    container_name: redis
    command: redis-server --databases 16
    ports:
      - "6379:6379"
    env_file:
      - .env
    volumes:
      - redis_data:/data

  api-gateway:
    build:
      context: ./
      dockerfile: ./apps/backend/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: npm run start:dev backend
  
  # TODO: make pg admin work through env variables
  # auto add server, even if not, make it work
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
  
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis
    volumes:
      - redisinsight_data:/db
    environment:
      - REDIS_URI=redis://redis:6379
      
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  redisinsight_data:
    driver: local